# Default initial positions for open_manipulator_pro's ros2_control fake system

initial_positions:
  # OMP in floor grasping position real
  joint1: 0.0
  joint2: 0.0
  joint3: 0.74
  joint4: 1.57
  joint5: 0.78
  joint6: -0.97
  base_link_gripper: 0.0
  gripper: 0.0
  gripper_sub: 0.32

